//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContestPark.Entities.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestParkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestParkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContestPark.Entities.AppResources.ContestParkResources", typeof(ContestParkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap bilgileri güncellendi..
        /// </summary>
        public static string AccountInfoUpdate {
            get {
                return ResourceManager.GetString("AccountInfoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ayarları.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düelloda yenilmeyi kabul ediyor musun?.
        /// </summary>
        public static string AdmitDefeat {
            get {
                return ResourceManager.GetString("AdmitDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakip Bekleniyor....
        /// </summary>
        public static string AwaitingOpponent {
            get {
                return ResourceManager.GetString("AwaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahis Tutarı.
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelle.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelledin..
        /// </summary>
        public static string Blocking {
            get {
                return ResourceManager.GetString("Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engellediğiniz kullanıcı listesi.
        /// </summary>
        public static string BlockUsersList {
            get {
                return ResourceManager.GetString("BlockUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Al.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategori kilitli. Kilidi açmak ister misiniz?.
        /// </summary>
        public static string CategoryLocked {
            get {
                return ResourceManager.GetString("CategoryLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ara.
        /// </summary>
        public static string CategorySearch {
            get {
                return ResourceManager.GetString("CategorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil ayarını değiştirirseniz uygulama yeniden başlatılacaktır. Dil ayarını değiştirmek istediğinize emin misiniz?.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil ayarı değiştirilirken bir hata meydana geldi. Lütfen tekrar deneyiniz..
        /// </summary>
        public static string ChangeLangError {
            get {
                return ResourceManager.GetString("ChangeLangError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil ayarı değiştirme.
        /// </summary>
        public static string ChangeLangTitle {
            get {
                return ResourceManager.GetString("ChangeLangTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eminim.
        /// </summary>
        public static string ChangeOkay {
            get {
                return ResourceManager.GetString("ChangeOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Değiştir.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sohbet Et.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sohbet görüldü yapılamadı..
        /// </summary>
        public static string ChatNotSeen {
            get {
                return ResourceManager.GetString("ChatNotSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlar.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat settings.
        /// </summary>
        public static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topla.
        /// </summary>
        public static string Collect {
            get {
                return ResourceManager.GetString("Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakibin duelloya karşı koyması bekleniyor.
        /// </summary>
        public static string CompetitorsIsExpectedResistDuel {
            get {
                return ResourceManager.GetString("CompetitorsIsExpectedResistDuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic concurrency failure, object has been modified..
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engellemeyi Onayla.
        /// </summary>
        public static string ConfirmBlock {
            get {
                return ResourceManager.GetString("ConfirmBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  isimli kullanıcıyı engellemek istediğinden emin misin?.
        /// </summary>
        public static string ConfirmBlockTitle {
            get {
                return ResourceManager.GetString("ConfirmBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriye ait geçmiş bulunmamakta..
        /// </summary>
        public static string ContestPostEmptyMessage {
            get {
                return ResourceManager.GetString("ContestPostEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest Store.
        /// </summary>
        public static string ContestStore {
            get {
                return ResourceManager.GetString("ContestStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapak resmi değiştir.
        /// </summary>
        public static string CoverPictureChange {
            get {
                return ResourceManager.GetString("CoverPictureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenilği.
        /// </summary>
        public static string Defeat {
            get {
                return ResourceManager.GetString("Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konuşmayı sil.
        /// </summary>
        public static string Deleteconversation {
            get {
                return ResourceManager.GetString("Deleteconversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ile aranızdaki sohbeti silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj sil?.
        /// </summary>
        public static string DeleteMessageTitle {
            get {
                return ResourceManager.GetString("DeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelleme listeniz boş..
        /// </summary>
        public static string DoNotBlockListIsEmpty {
            get {
                return ResourceManager.GetString("DoNotBlockListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkmak istiyor musunuz?.
        /// </summary>
        public static string DoYouWantToToQuit {
            get {
                return ResourceManager.GetString("DoYouWantToToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berabere.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düello.
        /// </summary>
        public static string Duel {
            get {
                return ResourceManager.GetString("Duel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duello teklifini silerseniz aynı zaman da yenilmiş sayılacaksınız. Yenilgiyi kabul ediyor musunuz?.
        /// </summary>
        public static string DuelDefeatMessage {
            get {
                return ResourceManager.GetString("DuelDefeatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış yaparsanız düelloyu kayıp etmiş sayılacaksınız yinede çıkmak istiyor musunuz?.
        /// </summary>
        public static string DuelExitQuestion {
            get {
                return ResourceManager.GetString("DuelExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düello Sonucu.
        /// </summary>
        public static string DuelResult {
            get {
                return ResourceManager.GetString("DuelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı ve şifre giriniz..
        /// </summary>
        public static string enterYourUsernamEAndPassword {
            get {
                return ResourceManager.GetString("enterYourUsernamEAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook adresimiz.
        /// </summary>
        public static string FacebookAddress {
            get {
                return ResourceManager.GetString("FacebookAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAKİP BUL.
        /// </summary>
        public static string FindOpponent {
            get {
                return ResourceManager.GetString("FindOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Et.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip edenler.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip edilenler.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Ettiğim Kategoriler.
        /// </summary>
        public static string FollowingCategories {
            get {
                return ResourceManager.GetString("FollowingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Edilenler.
        /// </summary>
        public static string FollowingProfile {
            get {
                return ResourceManager.GetString("FollowingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal ağlarda bizi takip edin.
        /// </summary>
        public static string FollowUsOnSocialNetworks {
            get {
                return ResourceManager.GetString("FollowUsOnSocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya eposta adresi giriniz..
        /// </summary>
        public static string ForgetYourPasswordLabel1 {
            get {
                return ResourceManager.GetString("ForgetYourPasswordLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta adresi veya kullanıcı adınızı giriniz. Hesap bilgilerinizi içeren bir e-posta alacaksınız..
        /// </summary>
        public static string ForgetYourPasswordLabel2 {
            get {
                return ResourceManager.GetString("ForgetYourPasswordLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi unutmuşum.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad soyad.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENEL.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzgünüz, beklenmedik bir hata oluştu yetkililere bildirildi..
        /// </summary>
        public static string GlobalErrorMessage {
            get {
                return ResourceManager.GetString("GlobalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Ayarlar.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram adresimiz.
        /// </summary>
        public static string InstagramAddress {
            get {
                return ResourceManager.GetString("InstagramAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name &apos;{0}&apos; is invalid, can only contain letters or digits..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diller.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beğen.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this login already exists..
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ile giriş yap.
        /// </summary>
        public static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaybetti.
        /// </summary>
        public static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Ayarları.
        /// </summary>
        public static string MessageSettings {
            get {
                return ResourceManager.GetString("MessageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj listeniz boş..
        /// </summary>
        public static string MessageYourListIsEmpty {
            get {
                return ResourceManager.GetString("MessageYourListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevler.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Sohbet.
        /// </summary>
        public static string NewChat {
            get {
                return ResourceManager.GetString("NewChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Görevler Yakında!.
        /// </summary>
        public static string NewMissionsComingSoon {
            get {
                return ResourceManager.GetString("NewMissionsComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altın yok.
        /// </summary>
        public static string NoGold {
            get {
                return ResourceManager.GetString("NoGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim sil.
        /// </summary>
        public static string NotificationRemove {
            get {
                return ResourceManager.GetString("NotificationRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu bildirimi silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string NotificationRemoveMessage {
            get {
                return ResourceManager.GetString("NotificationRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirimler.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski Şifre.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başka Rakip.
        /// </summary>
        public static string OtherOpponent {
            get {
                return ResourceManager.GetString("OtherOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DİĞER KULLANICILAR.
        /// </summary>
        public static string OtherUsers {
            get {
                return ResourceManager.GetString("OtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Ayarları .
        /// </summary>
        public static string PictureSettings {
            get {
                return ResourceManager.GetString("PictureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil resmi değiştir.
        /// </summary>
        public static string ProfilePictureChange {
            get {
                return ResourceManager.GetString("ProfilePictureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düğmeye basarak Kuralları kabul etmiş olursunuz..
        /// </summary>
        public static string PushTheButtonRulesYouAgree {
            get {
                return ResourceManager.GetString("PushTheButtonRulesYouAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorular.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip ettiğin kimse yok. Git birilerini takip et!.
        /// </summary>
        public static string RankFollowingNull {
            get {
                return ResourceManager.GetString("RankFollowingNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelli kaldır.
        /// </summary>
        public static string RemoveBlock {
            get {
                return ResourceManager.GetString("RemoveBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstek ve Şikayet.
        /// </summary>
        public static string RequestsAndComplaints {
            get {
                return ResourceManager.GetString("RequestsAndComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerekli alanları doldurunuz..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karşı koy.
        /// </summary>
        public static string Resist {
            get {
                return ResourceManager.GetString("Resist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rövanş.
        /// </summary>
        public static string Revenge {
            get {
                return ResourceManager.GetString("Revenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puan.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı ara....
        /// </summary>
        public static string SearchPeople {
            get {
                return ResourceManager.GetString("SearchPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu seçiniz ve mesajınızı yazınız..
        /// </summary>
        public static string SelectATtopicAndWriteYourMessage {
            get {
                return ResourceManager.GetString("SelectATtopicAndWriteYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim İşlemi Seçiniz.
        /// </summary>
        public static string SelectImageProcessing {
            get {
                return ResourceManager.GetString("SelectImageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Seçiniz.
        /// </summary>
        public static string SelectProcess {
            get {
                return ResourceManager.GetString("SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi gönder gelsin!.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir yarışmacı bulunamadı. Böyle bir kullanıcı olmayabilir yada hesabını dondurmuş olabilir..
        /// </summary>
        public static string ServerMessage_contestantFound {
            get {
                return ResourceManager.GetString("ServerMessage_contestantFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi kendiniz engelleyemezsiniz..
        /// </summary>
        public static string ServerMessage_doNotBlockToYourself {
            get {
                return ResourceManager.GetString("ServerMessage_doNotBlockToYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapak fotoğrafı silinemedi..
        /// </summary>
        public static string ServerMessage_dontRemoveCoverPicture {
            get {
                return ResourceManager.GetString("ServerMessage_dontRemoveCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düello yenilme işlemi gerçekleşmedi..
        /// </summary>
        public static string ServerMessage_duelRenewalProcessDidNotHappen {
            get {
                return ResourceManager.GetString("ServerMessage_duelRenewalProcessDidNotHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta adresiniz düzgün formatta değil..
        /// </summary>
        public static string ServerMessage_emailFormating {
            get {
                return ResourceManager.GetString("ServerMessage_emailFormating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta maksimum 255 karakter olmalıdır..
        /// </summary>
        public static string ServerMessage_emailMaxLength {
            get {
                return ResourceManager.GetString("ServerMessage_emailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta alanını doldurmak zorunludur..
        /// </summary>
        public static string ServerMessage_emailRequiredFields {
            get {
                return ResourceManager.GetString("ServerMessage_emailRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad maksimum 255 karakter olmalıdır..
        /// </summary>
        public static string ServerMessage_fullNameMaxLength {
            get {
                return ResourceManager.GetString("ServerMessage_fullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad minimum 3 karakter ve üzeri olmalıdır..
        /// </summary>
        public static string ServerMessage_fullNameMinLength {
            get {
                return ResourceManager.GetString("ServerMessage_fullNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad alanını doldurmak zorunludur..
        /// </summary>
        public static string ServerMessage_fullNameRequiredFields {
            get {
                return ResourceManager.GetString("ServerMessage_fullNameRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altın miktarınız yeterli değil..
        /// </summary>
        public static string ServerMessage_insufficientGold {
            get {
                return ResourceManager.GetString("ServerMessage_insufficientGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu bağlantıyı zaten beğenmişsiniz..
        /// </summary>
        public static string ServerMessage_inThisPostYouHaveAlreadyLiked {
            get {
                return ResourceManager.GetString("ServerMessage_inThisPostYouHaveAlreadyLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Yanlış!.
        /// </summary>
        public static string ServerMessage_keyFalse {
            get {
                return ResourceManager.GetString("ServerMessage_keyFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj arka plan resmi yapıldı..
        /// </summary>
        public static string ServerMessage_messagesWasBackgroundImage {
            get {
                return ResourceManager.GetString("ServerMessage_messagesWasBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre ve şifre tekrarla eşleşmiyor..
        /// </summary>
        public static string ServerMessage_notEqualsConfirmPassword {
            get {
                return ResourceManager.GetString("ServerMessage_notEqualsConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim id size ait değil..
        /// </summary>
        public static string ServerMessage_notificationIdWasNotYou {
            get {
                return ResourceManager.GetString("ServerMessage_notificationIdWasNotYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eski şifre ve yeni şifre 8 karakter üzeri olmalıdır..
        /// </summary>
        public static string ServerMessage_oldPasswordAndNewPasswordMinLength {
            get {
                return ResourceManager.GetString("ServerMessage_oldPasswordAndNewPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu bilgilere ait üyemiz bulunmamaktadır..
        /// </summary>
        public static string ServerMessage_ourRegisteredMembersOfThisInformationDoesNotExist {
            get {
                return ResourceManager.GetString("ServerMessage_ourRegisteredMembersOfThisInformationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz maksimum 32 karakter olmalıdır..
        /// </summary>
        public static string ServerMessage_passwordMaxLength {
            get {
                return ResourceManager.GetString("ServerMessage_passwordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz minimum 8 karakter ve üzeri olmalıdır..
        /// </summary>
        public static string ServerMessage_passwordMinLength {
            get {
                return ResourceManager.GetString("ServerMessage_passwordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre alanını doldurmak zorunludur..
        /// </summary>
        public static string ServerMessage_passwordRequiredFields {
            get {
                return ResourceManager.GetString("ServerMessage_passwordRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen profil resminizin uzantısı (.jpg, .bmp, .png) uzantılı olmalı..
        /// </summary>
        public static string ServerMessage_pictureFormat {
            get {
                return ResourceManager.GetString("ServerMessage_pictureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu resim size ait değil bu yüzden silemezsiniz..
        /// </summary>
        public static string ServerMessage_pictureIsNotYours {
            get {
                return ResourceManager.GetString("ServerMessage_pictureIsNotYours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenilen soru bulunamadı..
        /// </summary>
        public static string ServerMessage_requestedQuestionNotFound {
            get {
                return ResourceManager.GetString("ServerMessage_requestedQuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail gönderilirken hata oluştu lütfen tekrar deneyiniz..
        /// </summary>
        public static string ServerMessage_sendMailErrorMessage {
            get {
                return ResourceManager.GetString("ServerMessage_sendMailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre gönderme işleminde bir hata oluştu..
        /// </summary>
        public static string ServerMessage_sendPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ServerMessage_sendPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek talebiniz iletildi en kısa zamanda size dönüş yapılacaktır. Teşekkür ederiz..
        /// </summary>
        public static string ServerMessage_supportMessage {
            get {
                return ResourceManager.GetString("ServerMessage_supportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joker bulunamadı..
        /// </summary>
        public static string ServerMessage_theJokerIsNotFound {
            get {
                return ResourceManager.GetString("ServerMessage_theJokerIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriyi zaten takip ettiniz..
        /// </summary>
        public static string ServerMessage_ThisCategoryFollowing {
            get {
                return ResourceManager.GetString("ServerMessage_ThisCategoryFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategorinin kilidini zaten açtınız..
        /// </summary>
        public static string ServerMessage_ThisCategoryOpen {
            get {
                return ResourceManager.GetString("ServerMessage_ThisCategoryOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriyi takip etmek için ilk önce klidi açmalısınız..
        /// </summary>
        public static string ServerMessage_ThisCateogoryUnlock {
            get {
                return ResourceManager.GetString("ServerMessage_ThisCateogoryUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu eposta adresi başka bir kullanıcı tarafından kullanılmış..
        /// </summary>
        public static string ServerMessage_thisEmailAddressUsedByAnotherUser {
            get {
                return ResourceManager.GetString("ServerMessage_thisEmailAddressUsedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu bağlantıya ait beğenme gözükmüyor..
        /// </summary>
        public static string ServerMessage_thisLinkUnLike {
            get {
                return ResourceManager.GetString("ServerMessage_thisLinkUnLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu resim size ait değil..
        /// </summary>
        public static string ServerMessage_thisPictureIsNotYours {
            get {
                return ResourceManager.GetString("ServerMessage_thisPictureIsNotYours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı zaten takip ediyor..
        /// </summary>
        public static string ServerMessage_thisUserAreAlreadyFollowing {
            get {
                return ResourceManager.GetString("ServerMessage_thisUserAreAlreadyFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kişiyi takip ediyor gözükmüyorsunuz..
        /// </summary>
        public static string ServerMessage_thisUserFollowing {
            get {
                return ResourceManager.GetString("ServerMessage_thisUserFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kişiyi zaten engellemişsiniz..
        /// </summary>
        public static string ServerMessage_thisUserIsAlreadyBlocked {
            get {
                return ResourceManager.GetString("ServerMessage_thisUserIsAlreadyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı başka kullanıcı tarafından kullanılmış..
        /// </summary>
        public static string ServerMessage_thisUserNameWasUsedByAnotherUser {
            get {
                return ResourceManager.GetString("ServerMessage_thisUserNameWasUsedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kişi ile aranızda engelleme var. Siz onu yada o sizi engellemiş olabilir..
        /// </summary>
        public static string ServerMessage_userBlocked {
            get {
                return ResourceManager.GetString("ServerMessage_userBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bilgileriniz mail adresinize gönderilmiştir..
        /// </summary>
        public static string ServerMessage_userInfoSendMailAdress {
            get {
                return ResourceManager.GetString("ServerMessage_userInfoSendMailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının engeli kaldırıldı..
        /// </summary>
        public static string ServerMessage_userLiftedTheBlock {
            get {
                return ResourceManager.GetString("ServerMessage_userLiftedTheBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınız maksimum 255 karakter olmalıdır..
        /// </summary>
        public static string ServerMessage_userNameMaxLength {
            get {
                return ResourceManager.GetString("ServerMessage_userNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınız minimum 3 karakter ve üzeri olmalıdır..
        /// </summary>
        public static string ServerMessage_userNameMinLength {
            get {
                return ResourceManager.GetString("ServerMessage_userNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre yanlış..
        /// </summary>
        public static string ServerMessage_UsernameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("ServerMessage_UsernameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı alanını doldurmak zorunludur..
        /// </summary>
        public static string ServerMessage_userNameRequiredFields {
            get {
                return ResourceManager.GetString("ServerMessage_userNameRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınızda türkçe karakter olamaz..
        /// </summary>
        public static string ServerMessage_userNameTurkishCharactersCanNot {
            get {
                return ResourceManager.GetString("ServerMessage_userNameTurkishCharactersCanNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi kendinizi takip edemezsiniz..
        /// </summary>
        public static string ServerMessage_youCannotFollowASelf {
            get {
                return ResourceManager.GetString("ServerMessage_youCannotFollowASelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi kendinize mesaj atamazsınız..
        /// </summary>
        public static string ServerMessage_youCanNotMessageToYourself {
            get {
                return ResourceManager.GetString("ServerMessage_youCanNotMessageToYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendi kendinizin engelini kaldıramazsınız..
        /// </summary>
        public static string ServerMessage_youCanNotRemoveTheBlockYourself {
            get {
                return ResourceManager.GetString("ServerMessage_youCanNotRemoveTheBlockYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oynamak için yeterli altınınız yok..
        /// </summary>
        public static string ServerMessage_youDoNotHaveEnoughGoldToPlay {
            get {
                return ResourceManager.GetString("ServerMessage_youDoNotHaveEnoughGoldToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcıyı engellememiş gözüküyorsunuz..
        /// </summary>
        public static string ServerMessage_youUserBlock {
            get {
                return ResourceManager.GetString("ServerMessage_youUserBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kişiyi takip ediyor gözükmüyorsunuz..
        /// </summary>
        public static string ServerMessages_thisUserFollowing {
            get {
                return ResourceManager.GetString("ServerMessages_thisUserFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaş.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstatislikler.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoride daha önce yarışan olmamış. İlk sırayı sen kapabilirsin!.
        /// </summary>
        public static string ThisCategoryRankNull {
            get {
                return ResourceManager.GetString("ThisCategoryRankNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunu beğenenler.
        /// </summary>
        public static string ThisLikes {
            get {
                return ResourceManager.GetString("ThisLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berabere.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter adresimiz.
        /// </summary>
        public static string TwitterAddress {
            get {
                return ResourceManager.GetString("TwitterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takibi Bırak.
        /// </summary>
        public static string UnFollow {
            get {
                return ResourceManager.GetString("UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beğenmekten Vazgeç.
        /// </summary>
        public static string UnLike {
            get {
                return ResourceManager.GetString("UnLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilidi Aç.
        /// </summary>
        public static string UnLock {
            get {
                return ResourceManager.GetString("UnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password set..
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout is not enabled for this user..
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya eposta.
        /// </summary>
        public static string UserNameOrEmail {
            get {
                return ResourceManager.GetString("UserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in role &apos;{0}&apos;..
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ayarları.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aramıza hoş geldiniz. Az sonra yönlendirme işlemi gerçekleşecek..
        /// </summary>
        public static string WelcomeAboard {
            get {
                return ResourceManager.GetString("WelcomeAboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanan.
        /// </summary>
        public static string Winning {
            get {
                return ResourceManager.GetString("Winning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriyi açmak için yeterli miktarda altınınız yok. Altın satın almak ister misiniz?.
        /// </summary>
        public static string YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory {
            get {
                return ResourceManager.GetString("YouDoNotHaveASufficientAmountOfGoldToOpenThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenildin!.
        /// </summary>
        public static string YouLose {
            get {
                return ResourceManager.GetString("YouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirim listeniz boş..
        /// </summary>
        public static string YourNotificationListIsEmpty {
            get {
                return ResourceManager.GetString("YourNotificationListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sen kazandın!.
        /// </summary>
        public static string YouWin {
            get {
                return ResourceManager.GetString("YouWin", resourceCulture);
            }
        }
    }
}
